__Data Science With Python__

<font color = Red>  __New Lesson__ </font> <br>
**`Python Libraries: <br>`**
- numpy
- Pandas
- Scipy
- matplotlib
- Scikit learn

In [21]:
#Shape Manipulation
import numpy as np
new_cyclist_trials = np.array([[12,12,15,14,17,18],[2,5,8,7,4,1]])

In [4]:
new_cyclist_trials

array([[12, 12, 15, 14, 17, 18],
       [ 2,  5,  8,  7,  4,  1]])

**`ravel()`**: Will faltten the array or data set

In [5]:
new_cyclist_trials.ravel()

array([12, 12, 15, 14, 17, 18,  2,  5,  8,  7,  4,  1])

In [14]:
new_cyclist_trials.reshape(6,2)

array([[12, 12],
       [15, 14],
       [17, 18],
       [ 2,  5],
       [ 8,  7],
       [ 4,  1]])

In [23]:
new_cyclist_trials.resize(4,3)

In [24]:
new_cyclist_trials

array([[12, 12, 15],
       [14, 17, 18],
       [ 2,  5,  8],
       [ 7,  4,  1]])

__Split and Stacking of arrays__

In [26]:
#this will vertically slice the array int equal parts provided
np.hsplit(new_cyclist_trials, 3)

[array([[12],
        [14],
        [ 2],
        [ 7]]),
 array([[12],
        [17],
        [ 5],
        [ 4]]),
 array([[15],
        [18],
        [ 8],
        [ 1]])]

In [39]:
new_cyclist_1 = np.array([[1, 2] ,[3, 4]])
new_cyclist_2 = np.array([[10, 20], [30, 40]])

In [40]:
np.hstack((new_cyclist_1, new_cyclist_2))

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [41]:
new_cyclist_1

array([[1, 2],
       [3, 4]])

In [42]:
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
array_with_ones = np.ones((2,2,2))
array_with_ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [44]:
#array with random numbers
array_with_empty = np.empty((4, 2))
array_with_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [48]:
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [49]:
twoD_array = oneD_array.reshape(3,5)
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
threeD_array = np.arange(27).reshape(3, 3, 3)
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [53]:
np_linspce = np.linspace(1, 10, 2)
np_linspce

array([ 1., 10.])

<font color = Red>  __New Lesson__ </font> <br>